# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 057fd2219636c14d37f72f0caf14bbbac63df884c2d285f0641abb5d4a9edc038ed6dba2460a2e9a4111d966a8608fac249b4e8c411540b441e52ac8133f7fa3

test:
  secret_key_base: 765d77b11d03e5f092e78c41894c909a45148019be40ffbf379908367e095a87573037c0e4ddabac8b91b56ce3028415d181b7bda22fffd309545e1e5c3be2f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
